server:
  port: 9004

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://ec2-34-249-247-7.eu-west-1.compute.amazonaws.com:5432/d9gbnqodkmje9u
    driver-class-name: org.postgresql.Driver
    username: rmybrvfrrtvmjz
    password: fd27eec2db9f2e974a6296324d0d1ad1dc9f71efdb884ece8da45de977872c13
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
    home-page-url: https://${eureka.instance.hostname}/

